In [2]:
import pandas as pd

df_ridership = pd.read_csv('../data/raw/cta_ridership.csv')
print("Ridership Shape:", df_ridership.shape)
print("Ridership Columns:", df_ridership.columns.tolist())
df_ridership.head()

Ridership Shape: (1048575, 4)
Ridership Columns: ['route', 'date', 'daytype', 'rides']

C:\Users\HP\AppData\Local\Temp\ipykernel_24044\1908260778.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ridership = pd.read_csv('../data/raw/cta_ridership.csv')

  route        date daytype  rides
0     1  05/14/2001       W  6,217
1     1  07-06-2001       W  6,590
2     1  01-04-2001       W  6,907
3     1  04/19/2001       W  6,568
4     1  10-04-2001       W  6,361

In [3]:
df_weather = pd.read_csv('../data/raw/weather_chicago.csv')
print("Weather Shape:", df_weather.shape)
print("Weather Columns:", df_weather.columns.tolist())
df_weather.head()

Weather Shape: (1099, 6)
Weather Columns: ['latitude', 'longitude', 'elevation', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation']

,latitude,longitude,elevation,utc_offset_seconds,timezone,timezone_abbreviation
0,41.862915,-87.64877,179,0,GMT,GMT
1,NaN,NaN,NaN,NaN,NaN,NaN
2,time,temperature_2m_max (°C),temperature_2m_min (°C),precipitation_sum (mm),rain_sum (mm),weather_code (wmo code)
3,01-01-2019,2.3,-1.5,6,3.6,73
4,02-01-2019,0,-3,0.1,0,71

In [4]:
df_stops = pd.read_csv('../data/raw/stops.txt')
print("Stops Shape:", df_stops.shape)
print("Stops Columns:", df_stops.columns.tolist())
df_stops.head()

Stops Shape: (11177, 9)
Stops Columns: ['stop_id', 'stop_code', 'stop_name', 'stop_desc', 'stop_lat', 'stop_lon', 'location_type', 'parent_station', 'wheelchair_boarding']

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding
0,1,1.0,Jackson & Austin Terminal,"Jackson & Austin Terminal, Northeastbound, Bus...",41.876330,-87.774111,0,NaN,1
1,2,2.0,5900 W Jackson,"5900 W Jackson, Eastbound, Southside of the St...",41.877075,-87.771324,0,NaN,1
2,4,4.0,5700 W Jackson,"5700 W Jackson, Eastbound, Southside of the St...",41.876992,-87.768264,0,NaN,1
3,6,6.0,Jackson & Lotus,"Jackson & Lotus, Eastbound, Southeast Corner",41.876521,-87.761452,0,NaN,1
4,7,7.0,5351 W Jackson,"5351 W Jackson, Eastbound, Southside of the St...",41.876560,-87.758931,0,NaN,1